# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1ab4f81b20faeaaa61f0fb8f6b11ea45b2c25864fe65d4d642254172295fb5d04a86f6359dca34a1f54d6ca8dda9c9d4ce2b2450cdd581a91f2608213db29b61

test:
  secret_key_base: cda522f2125059d285a9583b5509a5100b5d9ddcf68fab5bda568e6a843ba91dfd805b1c3a3c7bd8758d52f47f889565e8dda3c4fe4f34c12a3abc5dcf150339

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
